### ISSUE TITLE
wrong type in README.md

### ISSUE THREAD

**Issue by Wenke-D** [ocaml-multicore/ocaml-effects-tutorial#12]
in the section 1.2. Basics

> The parameter k, is the delimited continuation between the point of performing the effect and the effect handler. The delimited continuation is like a dynamically defined function, that can be called and returns a value. The type of k in this case is (int, int) continuation, which says that the continuation expects an integer to continue (the first type parameter), and returns with an integer (the second type parameter).

I believe the type of **k** should be `(int, unit) continuation` instead of `(int, int) continuation` as the function `sum_up` does not return value.

**Comment by dhil** [comment]
Thanks! Yes, the given type is incorrect. But your reasoning is not correct. The second type argument of the `continuation` type constructor is the return type of the handler, not the handled computation, meaning the return type of `sum_up` is irrelevant. We can deduce that the handler returns unit from looking at the `exnc` clause.

**Comment by Wenke-D** [comment]
Thanks for the clarification!

I am still new to the effect Module, could you please explain why the second type argument is the return type of the handler instead of the one of the computation?

If I understand correctly, the `('a, 'b) continuation` represents the computation left to finish when we perform an effect. We need a data of type `'a` to resume the left computation, because we sort of took a break when we perform the effect. It feels more nature that `'b` is the return type of the computation instead of the handler.

Thanks in advance

**Comment by dhil** [comment]
The correct reading of `('a, 'b) continuation` depends on the origin of the continuation. If the continuation was captured "shallowly" then you are correct that `'b` would be instantiated to the same type as the remainder of the handled computation. If it is captured "deeply" then the handler itself is embedded in the continuation, in this case `'b` is instantiated to the return type of the handler (because the handler is run as part of the continuation). 

The example uses a deep handler, hence `'b` should be the return type of the handler.

([This paper](https://dhil.net/research/papers/shallow_effect_handlers-extended-aplas2018.pdf) may interest you, it discusses the differences between shallow and deep handlers.)

**Comment by Wenke-D** [comment]
Thanks for the information
